Redesign cropping mechanism
sysprog21/vcam pull request #30
Opened 2022-06-21 15:15 UTC by kevinshieh0225

In the original version, by setting different size between resolution
and bytesperline, vcam can simulate cropping function on the screen.
However there is three main drawbacks:

1. vcam crop left-top partition of the screen, which in most
cases users would expect for the middle region.
2. The origin implementation is lack of expansibility to offer user
to choose their region of interest.
3. vcam doesn't make good use of the `var` information in fb device.

By speculate how FFmpeg operate in [`fbdev_enc.c`](https://github.com/FFmpeg/FFmpeg/blob/25c8507818d8559a6654a5b30a0f8aae11a48181/libavdevice/fbdev_enc.c#L100), I rewrite the
cropping mechanism by using fbdev information including `x/yres`,
`x/yres_virtual`, `x/yoffset`. Instead of copy all the information
sended from users, only select those we want to display to
`copy_from_user`.

Current version obtains the following improvement:
1. vcam is able to crop the middle region of the picture.
2. This version has the potential to offer user to choose their
region of interest, and will be my future work.
3. This version can finally pass all the v4l2-compliance when we allow
`cropping` and `scaling` together.

2022-06-22 01:44 UTC, jserv commented on fb.c
> +#define mix(x, y)            \
You can define the simplified `min` macro and add comments for `TODO`.

2022-06-22 03:42 UTC, jserv commented on device.h
> +    size_t xbar;
Rewrite as
```c
size_t xbar, ybar;
```

2022-06-22 03:44 UTC, jserv commented on fb.c
> +        /* Assume that user should write in each frame independently,
Is it safe for multithreaded writes?

2022-06-26 05:16 UTC, jserv commented on fb.c
> +        if ((buf->xbar == line_vir && buf->ybar == y_vir - 1) ||
I don't really get the idea behind `buf->ybar == y_vir - 1`. Can you explain?

2022-06-27 10:57 UTC, jserv commented on fb.c
> +    if (dev->input_format.pixelformat == V4L2_PIX_FMT_RGB24) {
Shall we add some comments to denote other pixel formats?

2022-06-27 10:59 UTC, jserv commented on fb.c
> +        /* After copied, check if buf->xbar reach the border and need to carry.
Improve the writing. Should be "After data is copied"
reach -> reaches.
need -> needs.

2022-06-27 10:59 UTC, jserv commented on fb.c
> +        /* Check if buf->ybar reach the border, which the per-frame information
Ditto.

2022-06-27 11:01 UTC, jserv commented on fb.c
> +        /* Check if buf->ybar reach the border, which the per-frame information
Improve the grammar.

2022-06-28 06:25 UTC, jserv requested changes
Indent code as clang-format expects.

2022-06-28 06:41 UTC, merged

2022-06-28 06:41 UTC, jserv commented
Thank @kevinshieh0225 for contributing!

2022-06-28 06:42 UTC, kevinshieh0225 commented
Thankyou!